"""empty message

Revision ID: 0f5caa6c18fe
Revises: 4879378157df
Create Date: 2021-12-02 14:07:55.468386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f5caa6c18fe'
down_revision = '4879378157df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('message_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'message', ['message_id'], ['id'])
    op.drop_column('comment', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_2', 'comment', 'course', ['course_id'], ['id'])
    op.drop_column('comment', 'message_id')
    # ### end Alembic commands ###
