"""empty message

Revision ID: 4879378157df
Revises: 7a314cb58be8
Create Date: 2021-12-02 10:18:40.758860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4879378157df'
down_revision = '7a314cb58be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('love_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'love_num')
    # ### end Alembic commands ###
