"""empty message

Revision ID: 7a314cb58be8
Revises: 583145881fd2
Create Date: 2021-12-01 14:26:45.481869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a314cb58be8'
down_revision = '583145881fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('title', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'title')
    # ### end Alembic commands ###
